apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-proj-kustomization
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  path: mypath # Add proper path
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-proj-git-repo
